// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clothings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClothing = `-- name: CreateClothing :one
INSERT INTO clothing (
    user_id,
    main_color_1_id,
    main_color_2_id,
    accent_color_id,
    clothing_category_id,
    clothing_type_id,
    brand,
    style,
    image_link
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, user_id, main_color_1_id, main_color_2_id, accent_color_id, clothing_category_id, clothing_type_id, brand, style, created_at, updated_at, deleted_at, image_link
`

type CreateClothingParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	MainColor1ID       pgtype.UUID `json:"main_color_1_id"`
	MainColor2ID       pgtype.UUID `json:"main_color_2_id"`
	AccentColorID      pgtype.UUID `json:"accent_color_id"`
	ClothingCategoryID pgtype.UUID `json:"clothing_category_id"`
	ClothingTypeID     pgtype.UUID `json:"clothing_type_id"`
	Brand              pgtype.Text `json:"brand"`
	Style              pgtype.Text `json:"style"`
	ImageLink          pgtype.Text `json:"image_link"`
}

func (q *Queries) CreateClothing(ctx context.Context, arg *CreateClothingParams) (*Clothing, error) {
	row := q.db.QueryRow(ctx, createClothing,
		arg.UserID,
		arg.MainColor1ID,
		arg.MainColor2ID,
		arg.AccentColorID,
		arg.ClothingCategoryID,
		arg.ClothingTypeID,
		arg.Brand,
		arg.Style,
		arg.ImageLink,
	)
	var i Clothing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainColor1ID,
		&i.MainColor2ID,
		&i.AccentColorID,
		&i.ClothingCategoryID,
		&i.ClothingTypeID,
		&i.Brand,
		&i.Style,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ImageLink,
	)
	return &i, err
}

const createClothingCategory = `-- name: CreateClothingCategory :one
INSERT INTO clothing_category (
    value
) VALUES (
    $1
)
RETURNING id, value, created_at, updated_at, deleted_at
`

func (q *Queries) CreateClothingCategory(ctx context.Context, value string) (*ClothingCategory, error) {
	row := q.db.QueryRow(ctx, createClothingCategory, value)
	var i ClothingCategory
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const createColor = `-- name: CreateColor :one
INSERT INTO color (
    hex_value,
    color_group_name
) VALUES (
    $1,
    $2
)
RETURNING id, hex_value, color_group_name, created_at, updated_at, deleted_at
`

type CreateColorParams struct {
	HexValue       string `json:"hex_value"`
	ColorGroupName string `json:"color_group_name"`
}

func (q *Queries) CreateColor(ctx context.Context, arg *CreateColorParams) (*Color, error) {
	row := q.db.QueryRow(ctx, createColor, arg.HexValue, arg.ColorGroupName)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.HexValue,
		&i.ColorGroupName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getClothingCategoryByValue = `-- name: GetClothingCategoryByValue :one
SELECT id, value, created_at, updated_at, deleted_at FROM clothing_category
WHERE value = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetClothingCategoryByValue(ctx context.Context, value string) (*ClothingCategory, error) {
	row := q.db.QueryRow(ctx, getClothingCategoryByValue, value)
	var i ClothingCategory
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getColorByHex = `-- name: GetColorByHex :one
SELECT id, hex_value, color_group_name, created_at, updated_at, deleted_at FROM color
WHERE hex_value = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetColorByHex(ctx context.Context, hexValue string) (*Color, error) {
	row := q.db.QueryRow(ctx, getColorByHex, hexValue)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.HexValue,
		&i.ColorGroupName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
