// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getValidOTPByUsernameAndToken = `-- name: GetValidOTPByUsernameAndToken :one
SELECT id, user_id, token, created_at, updated_at, expired_at FROM otp
WHERE user_id = $1 AND token = $2 AND expired_at > NOW() LIMIT 1
`

type GetValidOTPByUsernameAndTokenParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Token  string      `json:"token"`
}

func (q *Queries) GetValidOTPByUsernameAndToken(ctx context.Context, arg *GetValidOTPByUsernameAndTokenParams) (*Otp, error) {
	row := q.db.QueryRow(ctx, getValidOTPByUsernameAndToken, arg.UserID, arg.Token)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return &i, err
}
