// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp (user_id, code)
VALUES ($1, $2)
RETURNING id, user_id, code, created_at, updated_at, expired_at
`

type CreateOTPParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Code   string      `json:"code"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg *CreateOTPParams) (*Otp, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.UserID, arg.Code)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return &i, err
}

const getValidOTPByUsernameAndCode = `-- name: GetValidOTPByUsernameAndCode :one
SELECT id, user_id, code, created_at, updated_at, expired_at FROM otp
WHERE user_id = $1 AND code = $2 AND expired_at > NOW() LIMIT 1
`

type GetValidOTPByUsernameAndCodeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Code   string      `json:"code"`
}

func (q *Queries) GetValidOTPByUsernameAndCode(ctx context.Context, arg *GetValidOTPByUsernameAndCodeParams) (*Otp, error) {
	row := q.db.QueryRow(ctx, getValidOTPByUsernameAndCode, arg.UserID, arg.Code)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return &i, err
}
