// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateClothing(ctx context.Context, arg *CreateClothingParams) (*Clothing, error)
	CreateClothingCategory(ctx context.Context, value string) (*ClothingCategory, error)
	CreateColor(ctx context.Context, arg *CreateColorParams) (*Color, error)
	CreateOTP(ctx context.Context, arg *CreateOTPParams) (*Otp, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error)
	GetClothingCategoryByValue(ctx context.Context, value string) (*ClothingCategory, error)
	GetColorByHex(ctx context.Context, hexValue string) (*Color, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (*Users, error)
	GetUserByUsername(ctx context.Context, username string) (*Users, error)
	GetUserByUsernameAndEmail(ctx context.Context, arg *GetUserByUsernameAndEmailParams) (*Users, error)
	GetValidOTPByCode(ctx context.Context, code string) (*Otp, error)
	SetIsVerifiedByUsername(ctx context.Context, arg *SetIsVerifiedByUsernameParams) (*Users, error)
}

var _ Querier = (*Queries)(nil)
