// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password, gender, dob)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password, created_at, updated_at, is_verified, gender, dob
`

type CreateUserParams struct {
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Gender   GenderType  `json:"gender"`
	Dob      pgtype.Date `json:"dob"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Gender,
		arg.Dob,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVerified,
		&i.Gender,
		&i.Dob,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, created_at, updated_at, is_verified, gender, dob FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*Users, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVerified,
		&i.Gender,
		&i.Dob,
	)
	return &i, err
}

const getUserByUsernameAndEmail = `-- name: GetUserByUsernameAndEmail :one
SELECT id, username, email, password, created_at, updated_at, is_verified, gender, dob FROM users
WHERE username = $1 OR email = $2 LIMIT 1
`

type GetUserByUsernameAndEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) GetUserByUsernameAndEmail(ctx context.Context, arg *GetUserByUsernameAndEmailParams) (*Users, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameAndEmail, arg.Username, arg.Email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVerified,
		&i.Gender,
		&i.Dob,
	)
	return &i, err
}

const getUserByUsernameAndPassword = `-- name: GetUserByUsernameAndPassword :one
SELECT id, username, email, password, created_at, updated_at, is_verified, gender, dob FROM users
WHERE username = $1 AND password = $2 LIMIT 1
`

type GetUserByUsernameAndPasswordParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetUserByUsernameAndPassword(ctx context.Context, arg *GetUserByUsernameAndPasswordParams) (*Users, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameAndPassword, arg.Username, arg.Password)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVerified,
		&i.Gender,
		&i.Dob,
	)
	return &i, err
}
